### ISSUE TITLE
Inquiry on the additional training configs

### ISSUE THREAD

**Issue by jinseokbae** [Tencent-RoboticsX/NCP#1]
Hello,

Thank you for sharing great work.

I'm curious about the training setups for additional experiments such as beta-vae imitation policy and the high-level policy for the beta-vae policy.
It would be very helpful if you could share the training configuration files.

Thank you.

Best,
Jinseok

**Comment by ZQX323** [comment]
Due to our original training being conducted in another RL-framework and beta-VAE not being our contribution, we have not used rl-games to replicate the beta-VAE results. However, I can provide some details about the beta-VAE training settings.

For the imitation policy, it is same as the VQ-Model, but includes an additional prior loss applied to the posterior distribution. The varying weights for the prior loss are detailed in our paper.

Regarding the high-level policy, it outputs a Gaussian distribution with trainable sigma parameters, initially set to 1.
